name: Update Exchange Rate

on:
  schedule:
    # Run at 16:00 UTC (18:00 Cairo time, which is UTC+2)
    - cron: '0 16 * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  update-rate:
    runs-on: ubuntu-latest
    steps:
      - name: Update Exchange Rate
        run: |
          curl -X POST \
            -H "x-api-key: ${{ secrets.UPDATE_API_KEY }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.VERCEL_URL }}/api/exchange-rate"